add_newline = false
format = "\\[$username@(white)$hostname\\]$directory$git_branch$character "

[username]
style_root = "bold red"
style_user = "bold cyan"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
style = "cyan"
format = "[$hostname]($style)"

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " ⃠"
read_only_style = "purple"
style = "bold green"
format = "[$path]($style)[$read_only]($read_only_style)"

[character]
format = " $symbol "
success_symbol = "[❯](bold yellow)"
error_symbol = "[❯](bold red)"

[git_branch]
format = ".[$branch]($style)"
style = "green"
